### ISSUE TITLE
Code review needed

### ISSUE THREAD

**Issue by chaputan** [PolytechLyon/isi3-test-chaput-cottet-tests#1]
Bonjour,

Pourriez-vous nous donner votre avis sur le TP et le rapport ?

Cordialement

**Comment by Slashgear** [comment]
Pour que cela soit complet, il faudrait trouver une solution pour eviter le if..elseif dans l'exercice du fizz buzz

**Comment by chaputan** [comment]
Bonsoir,

Voici une nouvelle version avec utilisation d'une énumération et d'un `BiFunction<Integer, Integer, Boolean>` afin d'éviter les conditions en chaîne.

**Comment by Slashgear** [comment]
👌
